name: Smart_Medicine_Box
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_screenutil: ^0.7.0
  page_transition: '^1.1.5'
  mailer: '^3.0.4'
  flutter_local_notifications: ^1.4.4+5
  rxdart: ^0.24.0
  flutter_datetime_picker: ^1.3.4
  timezone: ^0.6.0
  intl : ^0.16.1
  shared_preferences: ^0.5.12+2
  flutter_blue: ^0.7.2
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  flutter_dotenv: ^2.1.0
  numberpicker: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - .env
    - images/
    - images/main_logo.png
    - images/setting.png

fonts:
  # - family: Raleway
  #   fonts:
        #     - asset: fonts/Raleway-Regular.ttf
        #     - asset: fonts/Raleway-Italic.ttf
        #       style: italic
- family: NotoSansKR
  fonts:
    - asset: assets/fonts/NotoSansKR-Regular.otf
    - asset: assets/fonts/NotoSansKR-Bold.otf
      weight: 500
    - asset: assets/fonts/NotoSansKR-Black.otf
      weight: 700